spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauthdb
    username: postgres
    password: qwerqwer
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # or create-drop for dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
